### ISSUE TITLE
compilation fails due to multiple definitions of `json_error_messages` 

### ISSUE THREAD

**Issue by aparcar** [blogic/ucentral-jsonschema#1]
Trying to compile this package results in the follow error:

```
jsonschema/build on  main via △ v3.18.4 took 7s 
❯ make
[ 20%] Building C object CMakeFiles/jsonschema.dir/jsonschema.c.o
[ 40%] Building C object CMakeFiles/jsonschema.dir/instance_validator.c.o
[ 60%] Building C object CMakeFiles/jsonschema.dir/schema_validator.c.o
[ 80%] Building C object CMakeFiles/jsonschema.dir/utils.c.o
[100%] Linking C executable jsonschema
/usr/bin/ld: CMakeFiles/jsonschema.dir/schema_validator.c.o:/home/user/src/ucentral/jsonschema/utils.h:72: multiple definition of `json_error_messages'; CMakeFiles/jsonschema.dir/instance_validator.c.o:/home/user/src/ucentral/jsonschema/utils.h:72: first defined here
/usr/bin/ld: CMakeFiles/jsonschema.dir/utils.c.o:/home/user/src/ucentral/jsonschema/utils.h:72: multiple definition of `json_error_messages'; CMakeFiles/jsonschema.dir/instance_validator.c.o:/home/user/src/ucentral/jsonschema/utils.h:72: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/jsonschema.dir/build.make:148: jsonschema] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/jsonschema.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

After removing the `json_error_messages` definition in `utils.h` it compiles fine.

```diff
diff --git a/utils.h b/utils.h
index 88d1ac0..63b9ca1 100644
--- a/utils.h
+++ b/utils.h
@@ -69,7 +69,7 @@ enum json_error_values {
        json_format_error
 };
 
-char *json_error_messages[MAX_ERR_MSGS];
+//char *json_error_messages[MAX_ERR_MSGS];
 
 /**
  * @brief Prints a colored message in the terminal.
```

Am I missing something?
